### PR TITLE
Opentest -> Loom

### PR DESCRIPTION
**Pull request by vhmth**
Hey Tyler!

As you might have been able to tell, I've been very heads down and pretty unresponsive (sorry about that!). We've been going through a rebrand from Opentest -> Loom. :-)

This updates our logo, and tonight or tomorrow I will finish up testing the `Store.ready` PR and get to the other conversations I've been missing out on. I'm also coming up with some nifty ideas to get all actions to run in the background script with little-to-no effort on the end user. :-) Haven't landed on anything super solid yet, but stay tuned!

### CODE REVIEW

**Comment by vhmth** [comment]
Saving you the hassle of opening a new tab to see the logo. :-)

Loom Logo

**Comment by tshaddix** [comment]
@vhmth That's awesome! Super excited for you guys!

Love the new brand and logo :)

**Comment by tshaddix** [comment]
Looking forward to hearing more about your ideas!

**Comment by vhmth** [comment]
Thank you @tshaddix! On multiple fronts. :-) I'll keep you posted.

**Pull request merged**
