### PR TITLE
Bump to version 1.3.3

### LINKED ISSUE #74: Cannot run tests
I am getting this error when running the tests: (full output is [here](https://gist.github.com/collinsauve/fd2675b866bb008ed2c47e23cdf478df).)

> '.' is not recognized as an internal or external command,
> operable program or batch file.

On commit f2eb46f80f35a4022174f8ce569cfedb4f6ed92e
Node: v7.3.0
npm: v3.10.10
OS: Windows 10 v1607 Build 14393.447
Running in MINGW32
Bash version:  4.3.46(2)-release (x86_64-pc-msys)

### PR DESCRIPTION
**Pull request by tshaddix**
Includes @collinsauve’s changes for running lint/test on windows.

Closes #74

### CODE REVIEW

**Comment by tshaddix** [comment]
@vhmth @collinsauve Merged @collinsauve's changes into master. This is the version bump. Once this is merged in, I'll publish to npm

**Comment by tshaddix** [comment]
@vhmth I'll merge once you LGTM <3

**Comment by vhmth** [comment]
Luna looked it over and gave it a paws-up

**Comment by tshaddix** [comment]
@vhmth Okay see I wasn't going to accept your review until Luna gave it a once over. I'm glad she's still checking our work. Who knows where we'd be without her!

**Pull request merged**
