### PR TITLE
Version 1.0.0

### LINKED ISSUE #31: Prepare Stable Release 1.0.0
I think we're at a point to move towards a "stable" (1.X.Y) release of react-chrome-redux. We are currently "unstable" (0.X.Y) in terms of [SemVer](http://semver.org/). This issue should be used to discuss any remaining public API changes which might be necessary before moving to 1.0.0.

### PR DESCRIPTION
**Pull request by tshaddix**
Fixes #31

### CODE REVIEW

**Comment by tshaddix** [comment]
@vhmth Mind taking a look at this? Not much to see here 💯

**Comment by vhmth** [comment]
Shiiiip :)

**Comment by tshaddix** [comment]
@vhmth Can you approve? :)

**Comment by tshaddix** [comment]
@vhmth Thanks!

And thank you for all of your help getting us here! It's been wonderful working with you.

**Comment by vhmth** [comment]
Definitely! I haven't really done much. Just that `react-redux` bug and some simple updates to the README. I really appreciate you creating this library and your continued support on it. The feeling is mutual. :-)

**Pull request merged**
