### PR TITLE
Update name to `chrome-redux`

### LINKED ISSUE #63: Consider dropping "React" from package name
This package originally included `react` in the package name because it provided utilities for working with react components.

That was very short lived and this package no longer has anything to do with `react`. This was brought up in #11 .

It would be pretty straight-forward to drop `react` from the package name:
- Publish current code under npm package `chrome-redux`
- Rename github repo to `chrome-redux`
- Add deprecation message to `react-chrome-redux` npm package pointing at `chrome-redux` for any version over `1.3.1`

What do you think @vhmth ?

### PR DESCRIPTION
**Pull request by tshaddix**
Fixes #63

### CODE REVIEW

**Comment by vhmth** [comment]
Is there any way to have aliases from `react-chrome-redux` -> `chrome-redux` in NPM?

**Comment by tshaddix** [comment]
@vhmth Not that I've seen. The best you can do is leave a deprecation warning. https://docs.npmjs.com/cli/deprecate

**Comment by tshaddix** [comment]
Yea this is going to be a bit of a headache for people to switch which is really a bummer... Going to need to do a find/replace on `react-chrome-redux`

**Comment by vhmth** [comment]
Yeah it does seem like deprecation warnings are the best way to go:

http://stackoverflow.com/a/28841779/696130

I'm ok with it being a bit of a headache in order to drop `react-`. Do you know which other bigger projects might be using this lib other than Loom? Maybe if it is going to be a pain and we do plan on supporting other extensions, we rename to `webext-redux` or something like that now to remove the need for another name change down the road?

**Comment by tshaddix** [comment]
GoGuardian's extension is the only other "large" extension I know of. That said, I've been hearing some rather large entities are using it in their extensions. Not sure if it is their production extension or something internal.

Maybe we do want to make the rename more generic... I don't think we've come up with a real plan for making it fully compatible, correct? We should do that before we do a rename for something with `webext`. I will open an issue now.

**Comment by vhmth** [comment]
Guess I should have been explicit. I really meant other than GG and Loom (usually I take GG as a given in my convos since you work there). That's also why I was careful to say "larger" rather than "large" since I still consider us pretty early on our journey. :-P Sounds good on opening the issue.

**Comment by tshaddix** [comment]
@vhmth Got it! I was using "large" to describe the extension complexity (I'm assuming you guys have a bit of complexity in there) :)

**Comment by AgrimPrasad** [comment]
In my opinion:

1. `webext-redux` would be a better name than `chrome-redux`, as we are planning to support the Web Extensions API.
2. We should wait for #65 to be fully resolved first before finalizing and changing the new name, lest it give new developers the idea that this library works perfectly with WebExtensions out of the box.

**Comment by vhmth** [comment]
@AgrimPrasad sounds like we're on the same page (at least I am - but seems like @tshaddix is too based on him wanting to support other extension environments). I actually would usually be opposed to a move like this, but this repo is pretty well-confined to the Chrome APIs, and I can see a corresponding API for Mozilla for each one we use. :0)

**Comment by tshaddix** [comment]
Agreed @vhmth and @AgrimPrasad ! Let's discuss in #65

**Pull request closed without merging**
