### PR TITLE
Store.ready

### PR DESCRIPTION
**Pull request by vhmth**
Still WIP. Haven't tested at all, and it seems like Travis is failing. :-P

### CODE REVIEW

**Comment by vhmth** [comment]
Travis is now passing, but I still need to test locally with the Opentest Chrome extension. Seems like a good sanity check especially since we now have multiple content scripts.

**Comment by tshaddix** [comment]
@vhmth Thanks for doing this! Looking forward to hearing your test results :)

**Comment by CaliAlec** [comment]
@vhmth How's the testing going? :)

**Comment by vhmth** [comment]
Tested this locally with our Loom extension and our new Gmail integration and it works. Not super surprising since this change is pretty small, but good to know. :-) I apologize for the holdup guys - things got crazy on my end again.

Looks like the tests are failing. Investigating what might be up there.

**Comment by vhmth** [comment]
Tests passing again. :)

**Comment by vhmth** [comment]
@tshaddix would you want me to add any additional tests for testing `Store.ready`? It uses the same mechanism as state updates, but it might be a good idea to add one or two lightweight tests.

**Comment by tshaddix** [comment]
@vhmth Awesome work! Yea, I think we should unit test any new functionality/features we add :)

**Comment by vhmth** [comment]
Hey guys added some es6 goodies to the tests and es6-ified all of them. Left y'all an overview video too:

https://www.useloom.com/share/2e149920e51311e68456953b30d4311d

**Comment by vhmth** [comment]
Hey Tyler seems like that Loom link is 404-ing. Did you delete or archive the video by any chance?

I can es6-ify all of the rest of the files that need to in the same sprint as the linting one if you'd like. If you feel strongly that that should go into this PR, I will absolutely do it today. :-) Just seemed like it makes more sense as one larger thing when we introduce linting.

**Comment by tshaddix** [comment]
@vhmth Yea, sadly. For whatever reason, the sound didn't come through on it. Must be a configuration with my mic.

No need to make full es6 happen in this PR!

Merging now.

**Comment by vhmth** [comment]
Yikes! I sent you an email.

Creating an issue for the linter.

**Comment by vhmth** [comment]
https://github.com/tshaddix/react-chrome-redux/issues/55

**Comment by salomao-rodrigues** [comment]
@tshaddix @vhmth
Hey guys

Any ideas on when this changes will be published to npm? - Sorry if that's been done.
I believe it hasn't happened yet so people following the documentation might have a hard time understanding why they get `store.ready is not a function`.

Thanks for the good work btw!

**Comment by tshaddix** [comment]
@salomao-rodrigues Sorry about that! I'll push them right now. I was combining this and another PR into a single release :)

**Comment by tshaddix** [comment]
@salomao-rodrigues #56

**Comment by salomao-rodrigues** [comment]
No worries @tshaddix , thanks a lot :)

**Comment by vhmth** [comment]
👊🏾

**Pull request merged**
